# https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml
trigger:
  - main

variables:
  - name: BuildContainerImage
    value: davidullrich/azurepipelineagent:node-20

# https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted
pool:
  name: Self-hosted

stages:
  - stage: build
    jobs:
      - job: build
        container:
          image: $(BuildContainerImage)

        steps:
          - checkout: self
            displayName: "Checkout repository"

          - task: UseDotNet@2
            displayName: "Use DotNet 7.x"
            inputs:
              packageType: sdk
              version: 7.x

          - task: CmdLine@2
            displayName: "Run Nuke"
            inputs:
              script: "./build.cmd Print Restore Compile Test --skip"
