# https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml
trigger:
  - main

variables:
  - name: BuildContainerImage
    value: davidullrich/azurepipelineagent:node-20
  - name: NUGET_PACKAGES
    value: $(Pipeline.Workspace)/.nuget/packages
  - name: DOTNET_NOLOGO
    value: 1

# https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted
pool:
  name: Self-hosted

stages:
  - stage: build
    jobs:
      - job: build
        container:
          image: $(BuildContainerImage)

        steps:
          - checkout: self
            displayName: "Checkout repository"
            fetchDepth: 0
            fetchTags: true

          - task: UseDotNet@2
            displayName: "Use DotNet 7.x"
            inputs:
              packageType: sdk
              version: 7.x

          # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/cache-v2
          # https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget
          - task: Cache@2
            displayName: "Cache NuGet packages"
            inputs:
              key: 'nuget | "$(Agent.OS)" | $(Build.SourcesDirectory)/**/packages.lock.json,!**/bin/**,!**/obj/**,!**/output/**'
              restoreKeys: |
                nuget | "$(Agent.OS)"
                nuget
              path: $(NUGET_PACKAGES)

          - task: CmdLine@2
            displayName: "Run Nuke"
            inputs:
              script: "./build.cmd Print Restore Compile Test Publish Zip PublishArtifacts --skip"
